name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: pnpm install

    - name: Run typecheck
      run: pnpm tsc --noEmit

    - name: Run lint
      run: pnpm eslint .

    - name: Run tests
      run: pnpm test

    - name: Run coverage
      run: pnpm test -- --coverage

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=your-organization
          -Dsonar.projectKey=your-project-key
          -Dsonar.sources=.
          -Dsonar.tests=.
          -Dsonar.test.inclusions=**/*.test.ts,**/*.spec.ts
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
